# Generated by Django 4.0.4 on 2023-05-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.FileField(upload_to='media/slider_images'),
        ),
    ]
