# Generated by Django 4.0.4 on 2023-05-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_slider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/banner_images')),
                ('discount_deal', models.CharField(max_length=200)),
                ('quote', models.CharField(max_length=200)),
                ('discount', models.IntegerField()),
                ('link', models.CharField(max_length=500)),
            ],
        ),
    ]
