# Generated by Django 4.0.4 on 2023-05-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bannerarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerarea',
            name='discount',
        ),
        migrations.AddField(
            model_name='bannerarea',
            name='offer_description',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
