# Generated by Django 4.0.4 on 2023-05-11 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_bannerarea_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerarea',
            name='link',
        ),
        migrations.RemoveField(
            model_name='bannerarea',
            name='offer_description',
        ),
    ]
