# Generated by Django 4.0.4 on 2023-05-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_bannerarea_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerarea',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bannerarea',
            name='offer_description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
