# Generated by Django 4.0.4 on 2023-05-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_product_section_productimages_product_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.CharField(max_length=100),
        ),
    ]
