# Generated by Django 4.0.4 on 2023-05-12 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_product_slug_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='core_Product',
        ),
    ]
