# Generated by Django 4.0.4 on 2023-05-15 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_product_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, default='', max_length=500, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section')),
            ],
            options={
                'db_table': 'core_UpcomingProduct',
            },
        ),
    ]
