# Generated by Django 4.0.4 on 2023-05-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_upcomingproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingproduct',
            name='image',
            field=models.ImageField(null=True, upload_to='media/upcoming_product_images'),
        ),
    ]
