# Generated by Django 4.0.4 on 2023-05-15 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_upcomingproductimages_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upcomingproductimages',
            old_name='image_url',
            new_name='image',
        ),
    ]
