# Generated by Django 4.0.4 on 2023-05-22 13:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_upcomingproductimages_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_date', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('posted_by', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/blogs')),
            ],
        ),
    ]
