# Generated by Django 4.0.4 on 2023-05-23 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_blog_posted_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='core_Blog',
        ),
    ]
